### PR TITLE
Convert to docker-compose file.

### LINKED ISSUE #1: Dockerfile doesn't work.
Unable to get the dockerfile to work from the assignment. The IP address given from the command doesn't have anything running on port 3000.

### PR DESCRIPTION
**Pull request by samwightt**
The docker file attached with the assignment doesn't work, so I updated it.

This pull request does the following:

* Converts the `Dockerfile` to a `Docker-compose.yml` file that makes it easier to set up the repo.
* Allows students to connect to the `nodejs` container via `localhost:3000` instead of having to use the container's IP address.
* Updates the README.md with information on how to use this new setup.

### CODE REVIEW

**Review by nicholascioli — COMMENTED** [review]
I don't see any reference to the `companies.json`  data being imported into the MongoDB image. Are you doing it elsewhere?

**Comment by samwightt** [comment]
I think I missed that in the original dockerfile, sorry! Added a dockerfile for the Mongo container, so it should work now. Also fixed the tabs issue. Didn't know my editor was inserting spaces!

**Comment by nicholascioli** [comment]
I like the changes and will pull them in now. For now, it'll be pulled into a separate branch labelled 'docker-compose' until I can figure out the issue with Windows.

Thanks again for your request!

**Comment by nicholascioli** [comment]
Move to docker compose

**Pull request merged**
